#!/usr/bin/env node

/**
 * IPC Type Generator
 *
 * Parses Electron IPC handler files and generates TypeScript
 * channel type definitions for type-safe IPC communication.
 *
 * Usage:
 *   tsx scripts/generate-ipc-types.ts --handlers <path> [options]
 *
 * Options:
 *   --handlers <path>   Path to IPC handler files (file or directory)
 *   --output <path>     Output path for generated type definitions
 *   --validate          Validate existing types match handlers (don't write)
 *   --json              Output JSON report
 *   -h, --help          Show help
 */

import { mkdir, readdir, readFile, stat, writeFile } from "fs/promises";
import path from "path";

const VERSION = "1.0.0";
const SCRIPT_NAME = "generate-ipc-types";

interface GenerateOptions {
  handlers: string;
  output: string;
  validate: boolean;
  json: boolean;
}

interface DiscoveredChannel {
  name: string;
  type: "handle" | "on";
  file: string;
  line: number;
}

interface ValidationMismatch {
  channel: string;
  issue: "missing-in-types" | "missing-in-handlers" | "type-mismatch";
  detail: string;
}

interface GenerationResult {
  handlersPath: string;
  outputPath: string;
  filesScanned: number;
  channels: DiscoveredChannel[];
  handleChannels: string[];
  onChannels: string[];
  generated: boolean;
  validation?: {
    valid: boolean;
    mismatches: ValidationMismatch[];
  };
}

const HANDLER_PATTERNS: Array<{
  name: string;
  pattern: RegExp;
  type: "handle" | "on";
}> = [
  {
    name: "ipcMain.handle",
    pattern: /ipcMain\.handle\(\s*['"]([^'"]+)['"]/g,
    type: "handle",
  },
  {
    name: "ipcMain.on",
    pattern: /ipcMain\.on\(\s*['"]([^'"]+)['"]/g,
    type: "on",
  },
];

async function findHandlerFiles(targetPath: string): Promise<string[]> {
  const files: string[] = [];
  const extensions = [".ts", ".tsx", ".js", ".mjs"];

  try {
    const stats = await stat(targetPath);

    if (stats.isFile()) {
      const hasExt = extensions.some((ext) => targetPath.endsWith(ext));

      if (hasExt && !targetPath.endsWith(".d.ts")) {
        files.push(targetPath);
      }

      return files;
    }

    if (stats.isDirectory()) {
      const entries = await readdir(targetPath, { withFileTypes: true });

      for (const entry of entries) {
        if (entry.name.startsWith(".") || entry.name === "node_modules") {
          continue;
        }

        const fullPath = path.join(targetPath, entry.name);

        if (entry.isFile()) {
          const hasExt = extensions.some((ext) => entry.name.endsWith(ext));

          if (hasExt && !entry.name.endsWith(".d.ts")) {
            files.push(fullPath);
          }
        } else if (entry.isDirectory()) {
          files.push(...(await findHandlerFiles(fullPath)));
        }
      }
    }
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      console.error(`Error: Path not found: ${targetPath}`);
      process.exit(1);
    }

    throw error;
  }

  return files;
}

function discoverChannels(
  filePath: string,
  content: string,
): DiscoveredChannel[] {
  const channels: DiscoveredChannel[] = [];
  const lines = content.split("\n");

  for (let lineNum = 0; lineNum < lines.length; lineNum++) {
    const line = lines[lineNum];
    const trimmedLine = line.trim();

    if (trimmedLine.startsWith("//") || trimmedLine.startsWith("/*")) {
      continue;
    }

    for (const handlerPattern of HANDLER_PATTERNS) {
      handlerPattern.pattern.lastIndex = 0;

      let match: RegExpExecArray | null;

      while ((match = handlerPattern.pattern.exec(line)) !== null) {
        channels.push({
          name: match[1],
          type: handlerPattern.type,
          file: filePath,
          line: lineNum + 1,
        });
      }
    }
  }

  return channels;
}

function generateTypeDefinitions(channels: DiscoveredChannel[]): string {
  const handleChannels = channels.filter(
    (channel) => channel.type === "handle",
  );
  const onChannels = channels.filter((channel) => channel.type === "on");

  let output = `// Auto-generated by ${SCRIPT_NAME}.ts
// Do not edit manually
// Re-run the generator when IPC handlers change

`;

  output += `export type IpcChannelMap = {\n`;

  if (handleChannels.length === 0) {
    output += `  // No invoke/handle channels discovered\n`;
  } else {
    for (const channel of handleChannels) {
      output += `  '${channel.name}': { args: unknown[]; return: unknown };\n`;
    }
  }

  output += `};\n\n`;

  output += `export type IpcEventMap = {\n`;

  if (onChannels.length === 0) {
    output += `  // No event channels discovered\n`;
  } else {
    for (const channel of onChannels) {
      output += `  '${channel.name}': { args: unknown[] };\n`;
    }
  }

  output += `};\n\n`;

  output += `export type IpcInvokeChannel = keyof IpcChannelMap;\n`;
  output += `export type IpcEventChannel = keyof IpcEventMap;\n\n`;

  output += `/**\n`;
  output += ` * Typed preload API interface.\n`;
  output += ` *\n`;
  output += ` * Use this interface with contextBridge.exposeInMainWorld\n`;
  output += ` * to ensure type-safe IPC from the renderer process.\n`;
  output += ` */\n`;

  output += `export interface TypedElectronAPI {\n`;

  if (handleChannels.length === 0 && onChannels.length === 0) {
    output += `  // No channels discovered - add IPC handlers and re-run\n`;
  }

  for (const channel of handleChannels) {
    const fnName = channelToFunctionName(channel.name);

    output += `  ${fnName}: (...args: IpcChannelMap['${channel.name}']['args']) => Promise<IpcChannelMap['${channel.name}']['return']>;\n`;
  }

  for (const channel of onChannels) {
    const fnName = channelToFunctionName(channel.name);

    output += `  ${fnName}: (callback: (...args: IpcEventMap['${channel.name}']['args']) => void) => void;\n`;
  }

  output += `}\n\n`;

  output += `// TODO: Replace 'unknown' types above with specific types for each channel.\n`;
  output += `// Example:\n`;
  output += `//   'app:get-version': { args: []; return: string };\n`;

  return output;
}

function channelToFunctionName(channel: string): string {
  return channel
    .replace(/[:-]+(.)/g, (_, char: string) => char.toUpperCase())
    .replace(/^(.)/, (_, char: string) => char.toLowerCase());
}

async function validateTypes(
  outputPath: string,
  channels: DiscoveredChannel[],
): Promise<{ valid: boolean; mismatches: ValidationMismatch[] }> {
  const mismatches: ValidationMismatch[] = [];

  let existingContent: string;

  try {
    existingContent = await readFile(outputPath, "utf8");
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      mismatches.push({
        channel: "*",
        issue: "missing-in-types",
        detail: `Type definition file not found: ${outputPath}`,
      });

      return { valid: false, mismatches };
    }

    throw error;
  }

  const existingChannelPattern = /'([^']+)':\s*\{/g;
  const existingChannels = new Set<string>();

  let match: RegExpExecArray | null;

  while ((match = existingChannelPattern.exec(existingContent)) !== null) {
    existingChannels.add(match[1]);
  }

  const discoveredNames = new Set(channels.map((channel) => channel.name));

  for (const channel of channels) {
    if (!existingChannels.has(channel.name)) {
      mismatches.push({
        channel: channel.name,
        issue: "missing-in-types",
        detail: `Channel '${channel.name}' found in ${channel.file}:${channel.line} but not in type definitions`,
      });
    }
  }

  for (const existing of existingChannels) {
    if (!discoveredNames.has(existing)) {
      mismatches.push({
        channel: existing,
        issue: "missing-in-handlers",
        detail: `Channel '${existing}' defined in types but no matching handler found`,
      });
    }
  }

  return {
    valid: mismatches.length === 0,
    mismatches,
  };
}

async function generate(options: GenerateOptions): Promise<GenerationResult> {
  const files = await findHandlerFiles(options.handlers);

  if (files.length === 0) {
    console.error(`No handler files found in: ${options.handlers}`);
    process.exit(1);
  }

  const allChannels: DiscoveredChannel[] = [];

  for (const file of files) {
    const content = await readFile(file, "utf8");
    allChannels.push(...discoverChannels(file, content));
  }

  const seen = new Set<string>();

  const uniqueChannels = allChannels.filter((channel) => {
    if (seen.has(channel.name)) {
      return false;
    }

    seen.add(channel.name);
    return true;
  });

  uniqueChannels.sort((a, b) => a.name.localeCompare(b.name));

  const handleChannels = uniqueChannels
    .filter((channel) => channel.type === "handle")
    .map((channel) => channel.name);

  const onChannels = uniqueChannels
    .filter((channel) => channel.type === "on")
    .map((channel) => channel.name);

  const result: GenerationResult = {
    handlersPath: options.handlers,
    outputPath: options.output,
    filesScanned: files.length,
    channels: uniqueChannels,
    handleChannels,
    onChannels,
    generated: false,
  };

  if (options.validate) {
    result.validation = await validateTypes(options.output, uniqueChannels);
  } else {
    const typeContent = generateTypeDefinitions(uniqueChannels);
    const outputDir = path.dirname(options.output);

    if (outputDir && outputDir !== ".") {
      await mkdir(outputDir, { recursive: true });
    }

    await writeFile(options.output, typeContent, "utf8");
    result.generated = true;
  }

  return result;
}

function formatHumanOutput(result: GenerationResult): void {
  console.log("\nIPC TYPE GENERATION REPORT");
  console.log("==========================\n");
  console.log(`Handlers path: ${result.handlersPath}`);
  console.log(`Output path:   ${result.outputPath}`);
  console.log(`Files scanned: ${result.filesScanned}`);
  console.log();

  console.log("DISCOVERED CHANNELS:");
  console.log();

  if (result.channels.length === 0) {
    console.log("  No IPC channels found.");
    console.log();
    return;
  }

  if (result.handleChannels.length > 0) {
    console.log("  Invoke/Handle channels:");

    for (const channel of result.handleChannels) {
      const info = result.channels.find((item) => item.name === channel);
      console.log(`    '${channel}' (${info?.file}:${info?.line})`);
    }

    console.log();
  }

  if (result.onChannels.length > 0) {
    console.log("  Event channels:");

    for (const channel of result.onChannels) {
      const info = result.channels.find((item) => item.name === channel);
      console.log(`    '${channel}' (${info?.file}:${info?.line})`);
    }

    console.log();
  }

  console.log(
    `  Total: ${result.handleChannels.length} invoke + ${result.onChannels.length} event = ${result.channels.length} channels`,
  );

  console.log();

  if (result.validation) {
    console.log("VALIDATION RESULT:");
    console.log();

    if (result.validation.valid) {
      console.log("  Types are in sync with handlers.");
    } else {
      console.log(
        `  ${result.validation.mismatches.length} mismatch(es) found:`,
      );
      console.log();

      for (const mismatch of result.validation.mismatches) {
        const label = `[${mismatch.issue.toUpperCase()}]`.padEnd(24);
        console.log(`  ${label} ${mismatch.detail}`);
      }
    }

    console.log();
  } else if (result.generated) {
    console.log(`Type definitions written to: ${result.outputPath}`);
    console.log();
    console.log("NEXT STEPS:");
    console.log("  1. Review the generated types");
    console.log(
      "  2. Replace 'unknown' types with specific types for each channel",
    );
    console.log("  3. Import and use TypedElectronAPI in your preload script");
    console.log();
  }
}

function printHelp(): void {
  console.log(`
${SCRIPT_NAME} v${VERSION} - IPC Type Generator

Usage:
  node scripts/generate-ipc-types.js --handlers <path> --output <path> [options]

Options:
  --handlers <path>   Path to IPC handler files (file or directory)
  --output <path>     Output path for generated type definitions
  --validate          Validate existing types match handlers; does not write
  --json              Output JSON report
  -h, --help          Show this help

Examples:
  node scripts/generate-ipc-types.js \\
    --handlers ./src/main/ipc-handlers.ts \\
    --output ./src/shared/ipc-types.generated.ts

  node scripts/generate-ipc-types.js \\
    --handlers ./src/main \\
    --output ./src/shared/ipc-types.generated.ts

  node scripts/generate-ipc-types.js \\
    --handlers ./src/main \\
    --output ./src/shared/ipc-types.generated.ts \\
    --validate

  node scripts/generate-ipc-types.js \\
    --handlers ./src/main \\
    --output ./src/shared/ipc-types.generated.ts \\
    --json

Exit Codes:
  0  Success
  1  Validation mismatch or execution error
`);
}

function parseArgs(args: string[]): GenerateOptions | null {
  if (args.length === 0 || args.includes("--help") || args.includes("-h")) {
    return null;
  }

  const options: GenerateOptions = {
    handlers: "",
    output: "",
    validate: false,
    json: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];

    if (arg === "--handlers" && i + 1 < args.length) {
      options.handlers = args[++i];
    } else if (arg === "--output" && i + 1 < args.length) {
      options.output = args[++i];
    } else if (arg === "--validate") {
      options.validate = true;
    } else if (arg === "--json") {
      options.json = true;
    }
  }

  if (!options.handlers) {
    console.error("Error: --handlers is required");
    return null;
  }

  if (!options.output) {
    console.error("Error: --output is required");
    return null;
  }

  return options;
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

async function main(): Promise<void> {
  const options = parseArgs(process.argv.slice(2));

  if (!options) {
    printHelp();
    process.exit(0);
  }

  const result = await generate(options);

  if (options.json) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    formatHumanOutput(result);
  }

  if (result.validation && !result.validation.valid) {
    process.exit(1);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
